framework:
    messenger:
        transports:
            # Producers
            business_event:
                dsn: 'gps:'
                options:
                    project_id: '%env(PUBSUB_PROJECT_ID)%'
                    topic_name: '%env(PUBSUB_TOPIC_BUSINESS_EVENT)%'
                    subscription_name: '%env(PUBSUB_SUBSCRIPTION_WEBHOOK)%'
                retry_strategy:
                    max_retries: 0
                serializer: pim_enrich.messenger.business_event_serializer

            # Consumers
            webhook:
                dsn: 'gps:'
                options:
                    project_id: '%env(PUBSUB_PROJECT_ID)%'
                    topic_name: '%env(PUBSUB_TOPIC_BUSINESS_EVENT)%'
                    subscription_name: '%env(PUBSUB_SUBSCRIPTION_WEBHOOK)%'
                retry_strategy:
                    max_retries: 0
                serializer: pim_enrich.messenger.business_event_serializer

        routing:
            'Akeneo\Pim\Enrichment\Bundle\Message\BusinessEvent': business_event
